'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.4927
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RSPUniwaxPlcSim.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property druk_aan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("druk_aan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property druk_uit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("druk_uit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_ln() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_ln", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_lp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_lp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_sn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_sn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_sp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_sp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ns_aan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ns_aan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ns_uit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ns_uit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ns_uit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ns_uit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rd_aan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rd_aan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property rd_uit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rd_uit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property res_aan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("res_aan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property res_aan1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("res_aan1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property res_uit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("res_uit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property res_uit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("res_uit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch-0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_aan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_aan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_aan1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_aan1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch-p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_uit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_uit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_uit1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_uit1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st-0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_ln() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st-ln", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_lp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st-lp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_n() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st-n", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_p() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st-p", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_sn() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st-sn", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property st_sp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("st-sp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
