'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("SolitaireDJ.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property display() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("display", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Image21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Image21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_C1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_C1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_D1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_D1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_L1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_L1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_R1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_R1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_U() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_U", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property joi_U1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("joi_U1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledG_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledG_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledG_off1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledG_off1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledG_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledG_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledR_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledR_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledR_off1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledR_off1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledR_off2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledR_off2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledR_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledR_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledY_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledY_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledY_off1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledY_off1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledY_off2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledY_off2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledY_off3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledY_off3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property ledY_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ledY_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_L() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_L", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_R() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_R", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sch_W() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sch_W", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Settings() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Settings", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SimOff() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SimOff", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property SimON() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SimON", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sol_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sol-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sol_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sol-2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sol_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sol-3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sol_3_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sol-3-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property sol_3a() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sol-3a", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Sol_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Sol-4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Update() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Update", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
